
[env]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_compat_mode = strict
lib_deps =
    bblanchon/ArduinoJson@^6.21.5

upload_speed = 1500000

monitor_speed = 115200
monitor_filters =
    default
    colorize
    time
    esp32_exception_decoder


